### ISSUE TITLE
Renaming of repo breaks packagist

### ISSUE THREAD

**Issue by xcompass** [IMSGlobal/caliper-php#335]
It seems this repo has been renamed from IMSGlobal/caliper-php-public to IMSGlobal/caliper-php. However, the package on packagist (https://packagist.org/packages/imsglobal/caliper) is still pointing to the old repo. It breaks the `composer install`.

**Comment by theAngryCoder** [comment]
@imsglobalAdmin Any idea on fixing this?

**Comment by lsloan** [comment]
I don't work for IMSGlobal, but I help maintain this library.  

@xcompass and @theAngryCoder, I'm sorry you've had trouble installing the package.  The good news is that a new version of Caliper (v1p2) will be released very soon.  I'm sure the new release will be listed in Packagist correctly.

In the meantime, I'll see whether I'm able to update Packagist for the current release.

**Comment by lsloan** [comment]
@xcompass and @theAngryCoder: Please try this again.  I understand my response to this issue has come incredibly late and it may no longer be convenient for you to to test this now.  If you can confirm that it works, I and the folks at IMS Global would appreciate it.  I'd like to be able to mark this issue as resolved.

I logged into Packagist and found that all I needed to do was click the "Edit" button and remove the "-public" suffix from the URL.  After that, I created a new project in my local environment, required imsglobal/caliper via Composer, and successfully used it in a small sample program.

@bracken and @joshuamcghee: It looks like nobody is reading messages sent to @imsglobalAdmin.  If there were, I bet somebody would have raised an alert about this within the organization or the maintainers of this repo.  Do you know whether that account should be a good contact?  Should some other account (@IMSGlobal/caliperworkers?) be advertised as the contact for this and other Caliper repos?

**Comment by bracken** [comment]
Thanks @lsloan, I have that packagist account pointing to an email that should get to me, and I'm subscribed to all caliper repos to hopefully not miss anything. But it's also easy to miss the emails.
May each readme

**Comment by xcompass** [comment]
@lsloan Thanks for fixing this. It works for me now.
